openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https://localhost/'
tags:
  - name: auth
    description: Auth Service
paths:
  /auth/register:
    post:
      tags:
        - auth
      description: Rejestruje użytkownika
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegister"
      responses:
        201:
          description: Poprawnie zarejestrowano
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID użytkownika
components:
  schemas:
    UserRegister:
      type: object
      required: [email, password, name, lastName, dateOfBirth, phoneNumber, address]
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          example: "2019-05-17"
        phoneNumber:
          type: number
        address:
          $ref: "#/components/schemas/Address"
    Role:
      type: string
      enum:
        - USER
        - EMPLOYEE
        - ADMIN
    Address:
      type: object
      properties:
        city:
          type: string
        street:
          type: string
        postal:
          type: string
        houseNumber:
          type: string
        apartmentNumber:
          type: string

